### ISSUE TITLE
How to find & run the EXE? *PLEASE HELP*

### ISSUE THREAD

**Issue by SixStringSamurai7** [kevinmurphy678/Stardew_Injector#12]
Hey man, sorry for the bother. Very new to modding, and I really like the idea of what this offers. 

Following the instructions you listed, I pasted all the files into Stardew Valley's main directory. 

But going through the files, I wasn't able to find the exe for the injector. Is it included in a separate download?

**Comment by kevinmurphy678** [comment]
https://github.com/kevinmurphy678/Stardew_Injector/releases
