### ISSUE TITLE
Movement speed

### ISSUE THREAD

**Issue by ghost** [kevinmurphy678/Stardew_Injector#13]
After the official patch to movement speed, this mod behaves differently. At 0 speed, it's slower than vanilla and the diagonal speed is faster than vanilla.

I tried removing it by just removing the line in the .config, but found that it doesn't actually disable the setting. Would it be possible to disable this entirely (or at least get it up to date with vanilla)? :)

**Comment by kevinmurphy678** [comment]
Yup, working on a fix now

**Comment by kevinmurphy678** [comment]
Try the latest release. Should fix it!

**Comment by ghost** [comment]
Seems like it works! That was fast, thanks a lot :)
