### ISSUE TITLE
Crash after a set time.

### ISSUE THREAD

**Issue by votex09** [kevinmurphy678/Stardew_Injector#14]
I haven't tested without fishing yet.  Seems to crash at about 5:30pm while fishing.
RunSpeed = 1 (Trying with 0 to see if anything changes)
EnableTweakedDiagonalMovement = True
EnableEasyFishing = True
EnableAlwaysSpawnFishingBubble = True (Crashed when False as well)
SecondsPerTenMinutes = 7 (Crashed on 8 as well)
EnableDebugMode = False

**Comment by votex09** [comment]
Crashes also when not fishing.  Just verified.

**Comment by SgtKnux** [comment]
Confirmed, also crashing for me.  Actions don't matter, it even crashed while I had it paused and doing something on another monitor.
Run speed has been 0, 3, and 4 with a crash.
Easy Fishing = True or False
AlwaysSpawnFishingBubble = True or False
SecondsperTen = 7 and 9
Debug = False

**Comment by votex09** [comment]
SgtKnux: "Confirmed, also crashing for me. Actions don't matter, it even crashed while I had it paused and doing something on another monitor."

This just happened to me as well.  It seems we definitely have the same issue.
Also, just for kicks I had to make sure the base game still worked and it does.  **_Not_** running the injector with all the files still in there made the game run fine.

**Comment by AthosThe3rd** [comment]
As far as I can tell the problem is with the injector .exe itself, no matter what you have modified it will crash after a while.

**Comment by kevinmurphy678** [comment]
I'll look into it. So the game crashes even without using any changed settings?

**Comment by votex09** [comment]
It crashes just by using the injector.  Never right away though.. It seems to be around a set amount of game time.  Maybe 30 minutes

**Comment by AthosThe3rd** [comment]
Just to clarify, the injector is the one that crashes taking the game with it.

**Comment by kevinmurphy678** [comment]
I just ran it for 45 minutes and it didn't crash. Not really sure how to fix this.When I play the game for longer I'll see if it crashes.

**Comment by votex09** [comment]
Is there a log to say what's happening when it crashes?  I tried looking for one if it existed but had no luck doing so.

**Comment by kevinmurphy678** [comment]
No but you can run the code from visual studio and when it crashes it will give you a detailed error log

**Comment by votex09** [comment]
If it makes any difference, I am using the GOG version... not steam.

**Comment by kevinmurphy678** [comment]
It shouldn't make any difference. I don't really know how to fix this unless I get the crash myself.  Maybe try downloading the source code and building / running it from that.

**Comment by AthosThe3rd** [comment]
not sure if this is the same issue everyone else is having but I managed to get a screencap of an error report. https://gyazo.com/37975d09eb76fe40db085ee682cd640d

**Comment by votex09** [comment]
Corrupted or missing audio file trying to play? This mod doesn't add media
like this correct?

**Comment by kevinmurphy678** [comment]
No it doesn't. Have you tried running as admin? I'm not sure whats causing it to get corrupted. With no settings enabled its just loading the game assembly and not editing it in anyway

**Comment by AthosThe3rd** [comment]
I was running as admin during this particular crash.

**Comment by kevinmurphy678** [comment]
Try the latest release. I changed it to compile as release instead of debug. It might fix the problem

**Comment by AthosThe3rd** [comment]
Got the same error as last one.

Also, is it normal for the prompt to have lines with "TREE: IsClient:False randomOutput: (random numbers)"?

not sure what else I could provide at this point.

**Comment by kevinmurphy678** [comment]
Yes, that is part of the game. I'm not sure what else to try.

**Comment by AthosThe3rd** [comment]
well thanks for the effort anyway.

**Comment by Gausch** [comment]
Same here. Game crashes after 15-30 minutes even without changes in the config file. Love the mod - fixing would be really awesome!

I use Windows 10 and run the injector.exe as admin.

**Comment by soupwizard** [comment]
I grabbed Stardew_Injector.0.033.rar yesterday and so far it's working great for me.  Only change I made to the config file was: 

SecondsPerTenMinutes = 15

Which makes the day longer, and makes for a much more relaxing game for me, less time pressure (and after the first spring, I head to the Spa in the afternoon to recharge my energy.  Even more relaxing).

**Comment by mrdorkus** [comment]
I've used .033 version on 1.04 (GoG's version) and played 4 days ingame, on the fifth day, it'll start crashing after 5 to 30 minutes of gameplay (it's random). It'll crash even when paused and game is left unattended (I played in window mode). I can never complete the 5th day because of this. I went and played the latest version 1.05 and same thing happens. Since you don't have any other version out now, I'm not sure how to remedy this issue. It did crash one time during day 3 I believe but now it crashes a lot. I'm not sure how else to give you more info as to figure out what's wrong with it.

Using Windows 7 64-bit Professional and only using the time per 10 min option. I've set it to 60 (which worked fine for the first 4 days).

**Comment by soupwizard** [comment]
To add info about my successful use:  using 0.033 on SDV 1.05 (Steam), on Windows 10 64bit with nvidia gtx 650, always full-screen with no steam overlay.  

 I'm now using SecondsPerTenMinutes = 15 and EnableEasyFishing True, still no crashes even with hours of play at a time.
