### ISSUE TITLE
Unable to load saves / make new game

### ISSUE THREAD

**Issue by Tyghter** [kevinmurphy678/Stardew_Injector#8]
I'm having trouble getting the injector working with either 1.03 or 1.03 with Hotfix 1. It behaves the same regardless of which I use. When I run the normal game exe, everything works fine. But when I run the injector, the game doesn't see any of my saves. I've repeatedly tried to start new games but run into other problems. If I try to create a character and select "Skip Intro," the game immediately crashes. If I watch the intro, I get to the farm before my character runs off screen which I realize is a known cutscene issue, but my run speed is set to 0 in the config file. I know that the injector is working to some extent since if I set the speed to something like 10, my character runs off the screen much faster. Either way, my only option at that point is to click the "Skip" button but that just crashes the game again exactly as if I'd skipped the whole intro. I've set both the game's exe and the injector to run with as an administrator with no effect.

I have absolutely no sense of rhythm and suck at the fishing minigame so any suggestions would be greatly appreciated.

**Comment by kevinmurphy678** [comment]
I'm not really sure. Have you tried the latest release?
